### ISSUE TITLE
I Can Has Release?

### ISSUE THREAD

**Issue by jherdman** [premailer/actionmailer_inline_css#27]
Rails 5.1 is out, and it really hates the current release of this gem due to its use of alias_method_chain. Would you mind cutting a release? Whilst you're at it, including the Github URL of this gem in the gemspec would be swell.

**Comment by jherdman** [comment]
Just following up on this, would a release be possible?

**Comment by Frexuz** [comment]
me2 :P

**Comment by stevelacey** [comment]
Yeah just to be clear, you've already fixed this in `master` but no one can install it without doing:
```
gem 'actionmailer_inline_css', github: 'premailer/actionmailer_inline_css'
```

**Comment by akzhan** [comment]
Trying to push new release 1.6.0, please inform if any bugs on deployment exists.

**Comment by stevelacey** [comment]
Thanks 😀 🙌  @akzhan can you tag the commit as well – and ideally, also tag the commit that was the previous version shipped too? If there are any issues with upgrades it'll help others figure out what changed. Looks like @jherdman has already ran into this #28.

**Comment by akzhan** [comment]
Done.
